In [9]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [47]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [24]:
scalar.item()

7

In [26]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [28]:
#2 []
vector.shape

torch.Size([2])

In [32]:
#MATRIX
MATRIX = torch.tensor([[7,8], [6,9]])
MATRIX.ndim

2

In [33]:
MATRIX[1]

tensor([6, 9])

In [35]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3], [5,9,16],[7,9,3]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 5,  9, 16],
         [ 7,  9,  3]]])

In [36]:
TENSOR.ndim

3

In [39]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 5,  9, 16],
        [ 7,  9,  3]])

In [41]:
#random tensors - the way many nn learn is they start w tensors full of random numbers and adjust random numbers to better represent data
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.2060, 0.3209, 0.0112, 0.5775],
        [0.7552, 0.8102, 0.5454, 0.3009],
        [0.4691, 0.8657, 0.5386, 0.6553]])

In [42]:
random_image_size_tensor = torch.rand(size=(224,224,3))# height, width, color channel (red, green, blue)